[package]
name = "diceprop"
version = "0.2.0"
edition = "2024"
rust-version = "1.87.0"
description = "Mathematical properties for random testing"
readme = "README.md"
repository = "https://github.com/jakoschiko/diceprop"
license = "MIT OR Apache-2.0"
keywords = ["algebra", "dicetest", "math", "property", "testing"]
categories = ["development-tools::testing"]

[dependencies]
dicetest = "0.4.0"
